Name:Sameeksha Kini

Roll No:J029

# Numpy

In [2]:
import numpy as np

In [3]:
A = np.array([[1, 4, 3], [2, 3, 7], [7, 1, 2]])
A

array([[1, 4, 3],
       [2, 3, 7],
       [7, 1, 2]])

In [4]:
B = np.array([[6, 2, 1], [3, 5, 8], [1, 1, 4]])
B

array([[6, 2, 1],
       [3, 5, 8],
       [1, 1, 4]])

In [5]:
C = np.array([[3, 1, 1], [9, 2, 6], [2, 2, 7]])
C

array([[3, 1, 1],
       [9, 2, 6],
       [2, 2, 7]])

## TASK 1:MATRIX PROPERTIES
### 1)NON COMMUTATIVE 
### A.B != B.A

In [6]:
AB = np.dot(A,B)
AB

array([[21, 25, 45],
       [28, 26, 54],
       [47, 21, 23]])

In [7]:
BA = np.dot(B,A)
BA

array([[17, 31, 34],
       [69, 35, 60],
       [31, 11, 18]])

* Exception : If either A/B is an identity matrix

In [8]:
I = np.identity(3, dtype = int)
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [9]:
BI = np.dot(B, I)
BI

array([[6, 2, 1],
       [3, 5, 8],
       [1, 1, 4]])

In [10]:
IB = np.dot(I, B)
IB

array([[6, 2, 1],
       [3, 5, 8],
       [1, 1, 4]])

### 2)ASSOCIATIVE
### A.(B.C) = (A.B).C

In [11]:
#A.(B.C)
A_BC = np.dot(A, np.dot(B, C))
A_BC

array([[378, 161, 486],
       [426, 188, 562],
       [376, 135, 334]])

In [12]:
#(AB).C
AB_C = np.dot(np.dot(A, B), C)
AB_C

array([[378, 161, 486],
       [426, 188, 562],
       [376, 135, 334]])

### 3)DISTRIBUTIVE PROPERTY
### A.(B + C) = A.B + A.C

In [13]:
# A.(B + C)
a = np.dot(A, (B + C))
a

array([[ 66,  40,  91],
       [ 75,  48, 123],
       [ 81,  34,  50]])

In [14]:
b = np.dot(A, B) + np.dot(A, C)
b

array([[ 66,  40,  91],
       [ 75,  48, 123],
       [ 81,  34,  50]])

## TASK 2:INVERSE OF MATRIX

In [15]:
invA = np.linalg.inv(A)
invA

array([[-0.00819672, -0.04098361,  0.1557377 ],
       [ 0.36885246, -0.1557377 , -0.00819672],
       [-0.1557377 ,  0.22131148, -0.04098361]])

In [16]:
invB = np.linalg.inv(B)
invB

array([[ 0.19354839, -0.11290323,  0.17741935],
       [-0.06451613,  0.37096774, -0.72580645],
       [-0.03225806, -0.06451613,  0.38709677]])

## TASK 3:SHOWING NUMPY IS FASTER THAN TRADITIONAL LOOPING

In [17]:
import time
import random

In [18]:
mat1 = np.array([[np.random.randint(0, 100) for j in range(1000)] for i in range(1000)])
mat2 = np.array([[np.random.randint(0, 100) for j in range(1000)] for i in range(1000)])

Traditional Looping

In [19]:
start = time.time()
res = np.array([[0 for i in range(1000)] for j in range(1000)])

for i in range(mat1.shape[0]):
    for j in range(mat2.shape[1]):
        res[i][j] = mat1[i][j] + mat2[i][j]
        
time_loop = time.time() - start
print(time_loop)    

0.9276354312896729


Numpy Array

In [20]:
start = time.time()
res_np = np.add(mat1, mat2)
time_np = time.time() - start
print(time_np)

0.000995635986328125


Hence we can see that numpy is much much faster than the traditional looping.